Header header

uint32 nodeId

uint16 msgType
uint16 msgId

uint32 responderId

uint8 rangeStatus
uint8 antennaMode
uint16 stopwatchTime

uint32 precisionRangeMm
uint32 coarseRangeMm
uint32 filteredRangeMm

uint16 precisionRangeErrEst
uint16 coarseRangeErrEst
uint16 filteredRangeErrEst

uint16 filteredRangeVel
uint16 filteredRangeVelErrEst

uint8 rangeMeasurementType
uint8 reserved

uint16 reqLEDFlags
uint16 respLEDFlags

uint16 noise
uint16 vPeak

uint32 coarseTOFInBins

uint32 timestamp
